profile:
  username: frefolli
  name: Francesco
  surname: Refolli
  topics:
    - Computer Science
    - Railways
  education:
    grade: "Master's Degree"
    topic: "Computer Science"
    year: "1st"
    institute: "Universita' degli studi di Milano Bicocca (just waiting to enroll :))"
  job:
    profession: "Software Engineer"
    place: "Binary System SRL"
  future: "add java.util.Scanner.nextChar() method"
skills:
  Languages:
    - Java
    - C++
    - C
    - Rust
    - Prolog
    - Lisp
    - Python
    - Javascript
    - Haskell
  Linux Distros:
    - Arch Linux
    - Fedora
    - Debian
    - Void
    - Slackware
    - Gentoo
  Text Editors:
    - Vim
    - Neovim
    - Emacs
    - Notepad++
    - VS Code
  Technologies:
    - Node JS
    - React JS
    - Docker
    - Java Spring
    - Facebook Proxygen
    - Make
    - CMake
    - Ninja
    - Meson
projects:
  Libraries:
    - libgc
    - libutils
    - libhyper
    - libclipp
    - liblexer
